# Everything in this section will be available as an environment variable
server = ""
database = ""
username = ""
password = ""

#auth0
clientId = "H79qgAie9uNwtLZNQyfK5lvtmlxJcZtE"
domain = "dev-u8gxdw325v1cs7ci.us.auth0.com"

#openai
openaiKey = "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"
openAiServiceKey = "528665b9b15a4932a38b66195769cbdb"

#cosmos
cosmosEndpoint = "https://neural.documents.azure.com:443/"
cosmosKey = "Crmg1tqOLDJZuQ0AutyCmZ8SveMKXJe3mvqpBzXwzhrg7dL3SC9bVFj2HOEVuPtjBAadskwt51gEACDbtTaTQg=="

#azure
storageContainerConnectionString = "DefaultEndpointsProtocol=https;AccountName=storagefinalsueastapp;AccountKey=zdWb66Q5S89XqBBUdHb6LMs8O3iuZ7aHTx/0tXOYURsBdypFj0+T0cITPOnZXysaJ45EloCFTwG2+ASt0t053w==;EndpointSuffix=core.windows.net"
userContainer = "containerusertest"
searchService = "s2standardsearchappaueast"
indexerName = "vectorindexerusertest7"
searchAdminKey = "vdk0oEwqnGc8mwPzZFfpyyVpD1bBI5V1Yryjp5KCM9AzSeBm9nYY"
embeddingModel = "text-embedding-ada-002"

#autogen
OAI_CONFIG_LIST = '[{"model": "gpt-4","api_key": "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"}]'
# You can also add other sections if you like.
# The contents of sections as shown below will not become environment variables,
# but they'll be easily accessible from within Streamlit anyway as we show
# later in this doc.
[my_other_secrets]
things_i_like = ["Streamlit", "Python"]
