# Everything in this section will be available as an environment variable
server = ""
database = ""
username = ""
password = ""

#auth0
clientId = "H79qgAie9uNwtLZNQyfK5lvtmlxJcZtE"
domain = "dev-u8gxdw325v1cs7ci.us.auth0.com"

#openai
openaiKey = "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"

#cosmos
cosmosEndpoint = "https://neural.documents.azure.com:443/"
cosmosKey = "Crmg1tqOLDJZuQ0AutyCmZ8SveMKXJe3mvqpBzXwzhrg7dL3SC9bVFj2HOEVuPtjBAadskwt51gEACDbtTaTQg=="

#azure
storageContainerConnectionString = "DefaultEndpointsProtocol=https;AccountName=storagedummyskillset;AccountKey=Y+4rmhV+Q0CrGMByYP6RSw2jI0IFhzrw993r+X8sNqwr0n8Dd/0bNYF7huAyKr18Kor06XCV2LV4+AStEYiS4w==;EndpointSuffix=core.windows.net"

# You can also add other sections if you like.
# The contents of sections as shown below will not become environment variables,
# but they'll be easily accessible from within Streamlit anyway as we show
# later in this doc.
[my_other_secrets]
things_i_like = ["Streamlit", "Python"]
