# Everything in this section will be available as an environment variable
server = ""
database = ""
username = ""
password = ""

#auth0
clientId = "H79qgAie9uNwtLZNQyfK5lvtmlxJcZtE"
domain = "dev-u8gxdw325v1cs7ci.us.auth0.com"

#openai
openaiKey = "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"
openAiServiceKey = "528665b9b15a4932a38b66195769cbdb"

#cosmos
cosmosEndpoint = "https://neural.documents.azure.com:443/"
cosmosKey = "Crmg1tqOLDJZuQ0AutyCmZ8SveMKXJe3mvqpBzXwzhrg7dL3SC9bVFj2HOEVuPtjBAadskwt51gEACDbtTaTQg=="

#azure
storageContainerConnectionString = "DefaultEndpointsProtocol=https;AccountName=storagedummyskillset;AccountKey=Y+4rmhV+Q0CrGMByYP6RSw2jI0IFhzrw993r+X8sNqwr0n8Dd/0bNYF7huAyKr18Kor06XCV2LV4+AStEYiS4w==;EndpointSuffix=core.windows.net"
searchService = "s2standardsearchappaueast"
searchAdminKey = "vdk0oEwqnGc8mwPzZFfpyyVpD1bBI5V1Yryjp5KCM9AzSeBm9nYY"
embeddingModel = "text-embedding-ada-002"

# You can also add other sections if you like.
# The contents of sections as shown below will not become environment variables,
# but they'll be easily accessible from within Streamlit anyway as we show
# later in this doc.
[my_other_secrets]
things_i_like = ["Streamlit", "Python"]
